version: '3.9'

services:
  react1:
    build: .
    container_name: r1
    ports:
      - "80:3000"
    volumes:
      - /Users/kurtpagal/University/Year3/Fall-Term/CMPT-353/Assignments/CMPT-353-A4:/app
    stdin_open: true
    tty: true
  node1:
    build: .
    container_name: A4
    ports:
      - "81:8080"
    volumes:
      - /Users/kurtpagal/University/Year3/Fall-Term/CMPT-353/Assignments/CMPT-353-A4:/app
    depends_on:
      mysql1:
        condition: service_started
    stdin_open: true
    tty: true
  mysql1:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    container_name: db1
    volumes:
      - ./CMPT-353-A4:/var/lib/mysql1
    environment:
      - MYSQL_ROOT_PASSWORD=admin
        